In [92]:
import tensorflow as tf

tensor_1d = tf.constant([2,3,4.])
print("1D-tensor:", tensor_1d)

tensor_2d = tf.constant([
    [1,2,3.],
    [3,5,-1]
    ], tf.float16)
print("Shape is the length (number of elements) of each of the axes of a tensor.")
print(tensor_2d)
print("Shape of 2d-tensor: ", tensor_2d.shape)

tensor_3d = tf.constant([
    [[18,2,3],
    [4,5,6]],
    [[11,12,13],
    [14,15,16.0]],
    ], tf.float64)
#tensor_2d = tensor_3d[0]
#print(tensor_3d)
#print("Tensor as np array: ", tensor_3d.numpy())

#print("Max element: ", tf.reduce_max(tensor_3d))
#print("Index of max element: ", tf.math.argmax(tensor_3d))
print("Tensor: ", tensor_3d[:,1,2]);
#print("Softmax: ", tf.argmax(tensor_2d[0]))

string_tensor = tf.constant(["One", "Two"])
tf.strings.join(string_tensor, separator=" ")


1D-tensor: tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)
Shape is the length (number of elements) of each of the axes of a tensor.
tf.Tensor(
[[ 1.  2.  3.]
 [ 3.  5. -1.]], shape=(2, 3), dtype=float16)
Shape of 2d-tensor:  (2, 3)
Tensor:  tf.Tensor([ 6. 16.], shape=(2,), dtype=float64)


<tf.Tensor: shape=(), dtype=string, numpy=b'One Two'>

Casted tensors

In [53]:
import tensorflow as tf

tensor = tf.constant([1,0,3.])
tf.cast(tensor, dtype=tf.bool)

<tf.Tensor: shape=(3,), dtype=bool, numpy=array([ True, False,  True])>

Ragged Arrays

In [18]:
rt=tf.ragged.constant([
 [3, 1, 4, 1],
 [],
 [5, 9, 2],
 [6],
 []
 ])
print(rt, rt.shape)

<tf.RaggedTensor [[3, 1, 4, 1], [], [5, 9, 2], [6], []]> (5, None)


Sparse Tensors

In [19]:
st1 = tf.sparse.SparseTensor(indices=[[0, 3], [2, 4]],
                      values=[10, 20],
                      dense_shape=[3, 10])
print(st1)

SparseTensor(indices=tf.Tensor(
[[0 3]
 [2 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([10 20], shape=(2,), dtype=int32), dense_shape=tf.Tensor([ 3 10], shape=(2,), dtype=int64))


Eye (Identity) tensor

In [63]:
eye_tensor = tf.eye(num_rows=3,
                    num_columns=None,
                    batch_shape=None,
                    dtype=tf.float16,
                    name=None)
print(3*eye_tensor)

tf.fill([2,3], 5)


tf.Tensor(
[[3. 0. 0.]
 [0. 3. 0.]
 [0. 0. 3.]], shape=(3, 3), dtype=float16)


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[5, 5, 5],
       [5, 5, 5]], dtype=int32)>

Tensors can be initialized from NumPy arrays

In [21]:
import tensorflow as tf
import numpy as np
a2D = np.array([[1,2,3,4], [5,6.,7,8 ]])
tensor_2d = tf.constant(a2D, tf.float32)
print(tensor_2d)
print(tf.convert_to_tensor(a2D))


tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32)
tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float64)


Broadcating

In [2]:
import tensorflow as tf
import numpy as np

M = np.ones((2, 3))
a = np.arange(3)
print(M, a)


[[1. 1. 1.]
 [1. 1. 1.]] [0 1 2]


Algebraic operations

In [93]:
import tensorflow as tf

with tf.device('GPU:0'):
  # mat1 = tf.constant([
  #     [1,2,3],
  #     [3,-2,4]
  #     ], tf.float32)
  mat1 = tf.constant([1.,2,3,3,-2,4], shape=(2,3))
  print(mat1)
  # mat2 = tf.constant([
  #     [1.], [2], [-2]
  # ], tf.float32)
  mat2 = tf.Variable([
      [1., 2,-2]
  ], tf.float32)
  print(mat2)
  mat3 = tf.matmul(mat1, mat2, transpose_a=False,transpose_b=True)
  print(mat3)



tf.Tensor(
[[ 1.  2.  3.]
 [ 3. -2.  4.]], shape=(2, 3), dtype=float32)
<tf.Variable 'Variable:0' shape=(1, 3) dtype=float32, numpy=array([[ 1.,  2., -2.]], dtype=float32)>
tf.Tensor(
[[-1.]
 [-9.]], shape=(2, 1), dtype=float32)


Operations

In [89]:
import tensorflow as tf

mat = tf.constant([1,2,3])
print(mat)
mat_exp = tf.expand_dims(mat, axis=0)
print(mat_exp)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)


Variables

In [85]:
tf.debugging.set_log_device_placement(True)

try:
  tf.Variable([1,2,3], name="Mark")
except Exception as e:
  print(f"{type(e).__name__}: {e}")